# Generated by Django 5.1.7 on 2025-03-10 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+8801234233566'. Up to 11 digits allowed.",
                        regex="^\\+?880?\\d{9,11}$",
                    )
                ],
            ),
        ),
    ]
